" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

Plug 'lervag/vimtex'

Plug 'christophermca/meta5'
" Initialize plugin system
call plug#end()

set showcmd
set mouse=a
syntax on
set background=dark
set tabstop=4
set shiftwidth=4
set expandtab
set nu
set relativenumber
set colorcolumn=80

" Mapping
map <F5> :NERDTreeToggle<CR>

let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'zathura'
colorscheme meta5
highlight ColorColumn ctermbg=235
