" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like
call plug#begin('~/AppData/Local/nvim-data/site/plugged')

" Make sure you use single quotes

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

Plug 'christophermca/meta5'

Plug 'lervag/vimtex'

" Initialize plugin system
call plug#end()

colorscheme meta5
syntax on

set showcmd
set mouse=a
set background=dark
set tabstop=4
set shiftwidth=4
set expandtab
set nu
set relativenumber
set ch=1
set autoindent
set smartindent
set wildmenu
set history=200
set tw=79
set colorcolumn=-6,+1
set foldmethod=indent
set nofoldenable

" Mapping
map <C-n> :NERDTreeToggle<CR>

let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'zathura'
